### ISSUE TITLE
UI doesnt show up

### ISSUE THREAD

**Issue by endstoff** [PainedPsyche/cui_character#16]
The UI does not show up.

I am using latest exm

esx_skin & skinchanger are disabled

Config.PrimaryIdentifier is set to "steam"

Config.ExtendedMode and Config.UseSteamID are both set to true

I am not using ESX Identity Integration

And I am getting only a errror after restarting the script:

![cui character fehler wild wild](https://user-images.githubusercontent.com/63933131/105392323-5da68a80-5c1b-11eb-93f6-77030b26cc4b.png)

**Comment by Em1tSan** [comment]
Exactly the same problem, but esx_identity integration is included.

**Comment by PainedPsyche** [comment]
> The UI does not show up.
> 
> I am using latest exm
> 
> esx_skin & skinchanger are disabled
> 
> Config.PrimaryIdentifier is set to "steam"
> 
> Config.ExtendedMode and Config.UseSteamID are both set to true
> 
> I am not using ESX Identity Integration
> 
> And I am getting only a errror after restarting the script:
> 
> ![cui character fehler wild wild](https://user-images.githubusercontent.com/63933131/105392323-5da68a80-5c1b-11eb-93f6-77030b26cc4b.png)

There was indeed a problem with incorrectly initialized values. Thanks for reporting. It's fixed now.

> Exactly the same problem, but esx_identity integration is included.
> 
> ```
> Creating script environments for cui_character
> Error loading script server/main.lua in resource cui_character: @cui_character/server/main.lua:47: attempt to index a nil value (global 'ESX')
> stack traceback:
> 	@cui_character/server/main.lua:47: in main chunk
> Failed to load script server/main.lua.
> Started resource cui_character
> ```

This is **NOT** the same problem. Wrong values and trying to compare with a nil value was a legit bug while your problem looks like ESX misconfiguration.

Closing as fixed.
