### ISSUE TITLE
Freeze after register is completed

### ISSUE THREAD

**Issue by Borea** [PainedPsyche/cui_character#18]
Hello!

I follow all the instructions of the config file but when a finish the register my player frezze and only i can move uf i relog. Any help of that?

**Comment by Borea** [comment]
Im trying to solve this but idk thats the problem. Any help?

**Comment by Borea** [comment]
Fixed by my own :D Thanks

**Comment by DougJudy69** [comment]
> Fixed by my own :D Thanks

What was it?

**Comment by Borea** [comment]
> > Fixed by my own :D Thanks
> 
> What was it?

I don't remember. I'm not develop for fivem anymore.
