### ISSUE TITLE
[BUG] Hair

### ISSUE THREAD

**Issue by Ruqen** [PainedPsyche/cui_character#19]
Weirdly hair part on "styles" doesn't show up?

![image](https://user-images.githubusercontent.com/73693641/106654152-cf31f180-65a8-11eb-981d-cdf97f9f3763.png)

**Comment by XvenDeR** [comment]
have u tried scrolling down?

**Comment by Ruqen** [comment]
I did. I downloaded the last version to ensure it wasn't my problem too.

**Comment by Ruqen** [comment]
Really weird...

**Comment by Ruqen** [comment]
Anyone figured it out?

**Comment by Ruqen** [comment]
It resolved itself weirdly.
