### ISSUE TITLE
[Markers] `z`  has infinite distance

### ISSUE THREAD

**Issue by Jonneis** [PainedPsyche/cui_character#21]
For some reason when you go on any marker (cloth/barber/identity/surgery) and you go UP or Down on the marker  you can still access the shop, the distance is infinite

**Comment by YisusOnDev** [comment]
Just toggle to true every useZ flag on GetDistanceBetweenCoords.

-->

GetDistanceBetweenCoords(
		x1: number, 
		y1: number, 
		z1: number, 
		x2: number, 
		y2: number, 
		z2: number, 
		useZ: boolean <-- true 
	);


<--

**Comment by Jonneis** [comment]
Thanks mate i know how to do it i just comment it so they will change that i guess we close that since is not big deal.
