### ISSUE TITLE
disappears weapon

### ISSUE THREAD

**Issue by Astro-lab1** [PainedPsyche/cui_character#24]
when i spawn i have no weapons and in the data base they are save i already add   TriggerEvent('esx:restoreLoadout') at client/main.lua it works properly but every can use glitch of bullets or when you add a weapon i will disappear again you have to reconnect the game to take it back or changing clothes everything that is related to skin pls help to fix this im sure its at line 500 *client/main.lua* (for me) 
    Citizen.CreateThread(function()
        while not playerLoaded do
            Citizen.Wait(100)
        end

        if firstSpawn then
            local preparingSkin = true
            local isPlayerNew = false

            ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
                TriggerEvent('esx:restoreLoadout')
                if skin ~= nil then
                    oldChar = skin
                    LoadCharacter(skin)
                else
                    TriggerEvent('esx:restoreLoadout')
                    oldChar = GetDefaultCharacter(true)
                    LoadCharacter(oldChar)
                    isPlayerNew = true
                end
                preparingSkin = false
            end) 
mine is like this but it has too many bugs : /

**Comment by PainedPsyche** [comment]
Should be fixed now.
