### ISSUE TITLE
Does it work for extended 1.1?

### ISSUE THREAD

**Issue by DonJoan** [PainedPsyche/cui_character#31]
Excuse me for releasing it as an issue I did not find any information on how to contact you

Please tell if it works for es_extended 1.1

**Comment by PainedPsyche** [comment]
No, it does not and making it work would be too much effort. 

es_extended 1.1 is very outdated now and you should switch to [extendedmode](https://github.com/extendedmode/extendedmode).

**Comment by DonJoan** [comment]
I use this updated version   https://github.com/esx-framework/es_extended/tree/d8112af6e6cc92e948795cd93b41be149836c5d1
