### ISSUE TITLE
Job Clothes

### ISSUE THREAD

**Issue by ChicoTeVee** [PainedPsyche/cui_character#32]
Hey, i have the issue actually, if i go to the Police Wardrobe and change into Police Outfit, my Charakter gets Broke.

Same with registered Items like Bulletproof Vest or something.

Anyone can tell me how to set new clothe parts for job with this script?

**Comment by ChicoTeVee** [comment]
Alright i found the Solution :)

#closed

**Comment by LlamaPalooza89** [comment]
What was the solution?

**Comment by iSentrie** [comment]
He probably didn't set color or set incomplete uniform.
