### ISSUE TITLE
A lot of player on the same spawn...

### ISSUE THREAD

**Issue by JeDebute01** [PainedPsyche/cui_character#46]
Everythink in the video ;)

https://clips.twitch.tv/SuperImpossibleLlamaTBTacoLeft-XkHu4IfZcorDp15w

**Comment by boermansjo** [comment]
Not sure if this is problem of the script.
We avoided this problem by making multiple spawning points (like 20-ish)
And spawn each player on an empty spot. (Just an idea for you :) )

**Comment by JeDebute01** [comment]
Where is possible to change it? I don't use maphipster or nothing... I don't see spawnpoint in CUI_character...

**Comment by josh-tf** [comment]
Solution we used in our character creator (different script, looking at moving to this) was set all other peds invisible when the character creator is open, that way they cant see each other - we also made them invincible and non clipable so players not creating a character can't kill or push them around etc
