### ISSUE TITLE
ESX_Legacy, ESX_Multicharacter & ESX_Identity

### ISSUE THREAD

**Issue by Arnz5050** [PainedPsyche/cui_character#47]
I've been trying to replace the current skinchanger with cui_character, however after i load into a new character with multicharacter, either esx_identity still shows up and won't disappear, once information and everything has been entered and you click accept, it leaves you frozen in place and unable to type or do anything over than quit.
I managed to hide/remove the esx identity ui or resource itself and i still have the issue of being frozen after character creation.

When loading into a previously made character and going to the barber shop, it all works as expected and accepting changes works as it should, but for now I have reverted to the old skinchanger etc until i can figure out a fix or get help with the issue upon registering a new character

(Dev build)

**Comment by thelindat** [comment]
This would be an issue with multicharacter. After making a new character you stay at the character selection screen and start designing your character, before getting teleported - this relies on an event callback from esx_skin which would not exist here.

If you remove the loop while waiting for esx_skin to be set then you should spawn in fine, though I cannot say for sure.

**Comment by Arnz5050** [comment]
Okay I'll have a look a little later on to see if I can get it working, do you know if this would be in the server or client folder?

**Comment by Arnz5050** [comment]
I've started using fivem-appearance, this is no longer relevant to me
