### ISSUE TITLE
[Suggestion] Wardrobe

### ISSUE THREAD

**Issue by LySoon** [PainedPsyche/cui_character#7]
Guess you can save outfits like esx_skin saves, because as i understand by checking some of the code..
lots of players will request Wardrobe feature back so why not giving that back to them?

Also Thanks for great release, a script that made with real love <3

**Comment by LySoon** [comment]
also would love to join ur Discord if there is one..

**Comment by PainedPsyche** [comment]
Wardrobe has been released:

https://github.com/PainedPsyche/cui_wardrobe
