### ISSUE TITLE
Date of birth not being retrieved

### ISSUE THREAD

**Issue by jaysgrant** [PainedPsyche/cui_character#9]
I'm seeing that on each reload of the game, a character's DOB is not being retrieved from the database, and populated into the character creator UI. Upon each load, I have to reset the DOB, and then click accept to move into the game. I have looked into the database, and confirmed it is being saved in the dateofbirth column within the user table. I am using the latest version of extendedmode, with the latest version of esx_identity.

When I say latest, each of them is a direct clone of the master branch in the respective repos.

DOB set in database, verified before entering the server:
![image](https://user-images.githubusercontent.com/33356568/103709537-bf5ec780-4f80-11eb-8f1e-d67ea4fc822c.png)

DOB field on entering the server of an already set character:
![image](https://user-images.githubusercontent.com/33356568/103709461-92121980-4f80-11eb-990f-3ddb0f33c8a8.png)

**Comment by CorleoneAlCapone** [comment]
I have the same Problem. It looks like the Problem is the Format of the DOB. My esx_identity is setup for yyyy/mm/dd but cui_character takes the Format mm/dd/yyyy. I have tried to modify esx_identity to match it but it doesnt really helped.

**Comment by jaysgrant** [comment]
I just pulled the fix into my dev server, and it works perfectly! Thank you for the very quick turnaround!
